<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJTSiNSt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJTSiNSt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJTSiNSt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJTSiNSt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJTSiNSt\App_KernelDevDebugContainer([
    'container.build_hash' => 'JTSiNSt',
    'container.build_id' => '706c80fe',
    'container.build_time' => 1579012321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJTSiNSt');
